### ISSUE TITLE
Get the basic FACTS workflow running! 

### ISSUE THREAD

**Issue by kdorheim** [kdorheim/hector-facts#1]
`kd_running` is branched off of dev

**Comment by kdorheim** [comment]
Using the `python3 runFACTS.py experiments/X.py` method to try launching the runs 

- [ ] ar5k14.rcp26 (#7)
- [ ] ar5k14.rcp45  (#7)
- [ ] ar5k14.rcp85  (#7)
- [x] bamber19.ssp245
- [x] bamber19.ssp585
- [ ] coupling.ssp119 (might be related to #6 & #3)
- [ ] coupling.ssp126 (might be related to #6 & #3)
- [ ] coupling.ssp245 (might be related to #6 & #3)
- [ ] coupling.ssp370 (might be related to #6 & #3)
- [ ] coupling.ssp585 (might be related to #6 & #3)
- [ ] coupling.ssp585.larmipextrap
- [x] dummy
- [x] dummy.input (I don't think that this is really supposed to do anything...)
- [x] emulandice.ssp585 (#6)
- [ ] esl.ssp126 (#5)
- [ ] esl.ssp585 (and probably #5)
- [x] fittedismip.ssp585
- [ ] global.coupling.ssp245 (#3 might be related to #6)
- [ ] larmip.ipccar6.ssp585 (#4)
- [x] onemodule
- [x]  tlm.global
- [x] tlm.local
